AWSTemplateFormatVersion: "2010-09-09"
Description: >
  create s3 bucket.

Parameters:
  BucketName:
    Type: String
    Default: testbucket
  SSEAlgorithm:
    Type: String
    Default: AES256

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::AccountId}-${BucketName}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !Sub SSEAlgorithm

Outputs:
  S3Url:
    Value: !Sub https://s3.console.aws.amazon.com/s3/buckets/${BucketName}/?region=${AWS::Region}&tab=overview
