AWSTemplateFormatVersion: "2010-09-09"
Description: >
  create route53 Record set for alias.
Parameters:
  HostedZoneName:
    Type: String
    default: test.local.
  AliasTargetDnsName:
    Type: String
  AliasTargetHostedZoneId:
    Type: String
    Description: reference. https://docs.aws.amazon.com/general/latest/gr/rande.html)
    Default: Z14GRHDCWA56QT
  RecordName:
    Type: String
    Default: hoge1.hoge.local.
  RecordType:
    Type: String
    Default: A
  VpcRegion:
    Type: String
    Default: ap-northeast-1

Resources:
  DnsRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !Sub dualstack.${AliasTargetDnsName}
        HostedZoneId: !Ref AliasTargetHostedZoneId
        EvaluateTargetHealth: false
      HostedZoneName: !Ref HostedZoneName
      Name: !Ref RecordName
      Type: !Ref RecordType
